'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useRouter } from 'next/navigation';
import { useBackendSession } from '@/hooks/useBackendSession';
import { useAuth } from '@/context/AuthContext';
import { useProfileContext } from '@/context/ProfileContext';
import type { AppProgress, UserProfile } from '@/types';
import type { CustomCategory } from '@/hooks/useCustomCategories';
import { CATEGORIES, GRADE_LEVELS } from '@/lib/vocabulary';
interface DashboardData { profiles: UserProfile[]; progresses: Record<string, AppProgress>; categories: CustomCategory[]; revision: number; studentAccounts: { email: string; profileId: string }[] }
const field='mt-1 min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3';
export function FamilyDashboard() {
 const router = useRouter();
 const { account: familyAccount, openAuthModal, logout }=useAuth();
 const { syncWithServer }=useProfileContext();
 const adminSession=useBackendSession();
 const account=adminSession.authenticated ? { id: 'backend_admin', displayName: 'Admin', role: 'admin' as const } : familyAccount;
 const endpoint=adminSession.authenticated ? '/api/admin/family' : '/api/family';
 const [data,setData]=useState<DashboardData | null>(null);
 const [message,setMessage]=useState(''); const [busy,setBusy]=useState(false);
 const [name,setName]=useState(''); const [grade,setGrade]=useState('lop1'); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [profileId,setProfileId]=useState('');
 const [word,setWord]=useState(''); const [meaning,setMeaning]=useState(''); const [topic,setTopic]=useState('Từ mới của gia đình');
 const [edit,setEdit]=useState<UserProfile | null>(null);
 useEffect(()=>{ if(account?.role !== 'parent' && account?.role !== 'admin')return; const c=new AbortController();fetch(endpoint,{signal:c.signal,cache:'no-store'}).then(r=>r.json()).then(d=>{if(d.success)setData(d);else setMessage(d.message);}).catch(()=>setMessage('Không tải được dữ liệu.'));return()=>c.abort();},[account?.id,account?.role,endpoint]);
 async function submit(body: unknown) {setBusy(true);setMessage('');try{const r=await fetch(endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.message);setData(result);await syncWithServer();setMessage('Đã lưu trên server.');return true;}catch(e){setMessage(e instanceof Error?e.message:'Không lưu được.');return false;}finally{setBusy(false);}}
 async function addWord(){if(!data||!word.trim()||!meaning.trim())return;const cats=structuredClone(data.categories);let cat=cats.find(c=>c.name_vi===topic.trim()&&c.gradeId===grade);if(!cat){cat={id:`custom_${crypto.randomUUID()}`,name_vi:topic.trim()||'Từ mới',name_en:'Family vocabulary',emoji:'📚',gradeId:grade,color:'from-orange-400 to-orange-500',gradient:'bg-orange-50',words:[],createdAt:new Date().toISOString(),sourceType:'manual'};cats.push(cat);}cat.words.push({id:`word_${crypto.randomUUID()}`,en:word.trim(),vi:meaning.trim(),phonetic:'',emoji:'📖',example_en:'',example_vi:''});if(await submit({action:'save_categories',categories:cats,revision:data.revision})){setWord('');setMeaning('');}}
 if(account?.role==='student')return <main className="p-8 text-center"><h1 className="text-xl font-bold">Khu vực dành cho phụ huynh</h1><p className="my-4">Học sinh học và xem tiến độ của mình tại trang học.</p><Link href="/" className="learning-button bg-orange-600 text-white">Về học bài</Link></main>;
 if(adminSession.loading)return <p role="status" className="p-8">Đang mở khu vực phụ huynh…</p>;
 if(!account)return <main className="mx-auto max-w-md p-8"><h1 className="text-2xl font-bold">Góc phụ huynh</h1><p className="my-4">Đăng nhập để quản lý học sinh, theo dõi tiến độ và thêm từ mới.</p><button className="learning-button bg-orange-600 text-white" onClick={()=>openAuthModal('login')}>Đăng nhập</button><button className="learning-button" onClick={()=>openAuthModal('register')}>Đăng ký phụ huynh</button></main>;
 return <main className="min-h-screen bg-slate-50 p-4 sm:p-8"><div className="mx-auto max-w-5xl space-y-6"><header className="flex flex-wrap justify-between gap-3"><div><Link href="/">← Trang học</Link><h1 className="mt-3 text-2xl font-bold">Góc phụ huynh · {account.displayName}</h1><Link href="/manage" className="learning-button border bg-white mt-3">Quản lý kho từ vựng</Link></div><button className="learning-button border bg-white" onClick={()=>{ if(adminSession.authenticated) router.push('/admin'); else void logout(); }}>{adminSession.authenticated ? 'Về quản trị' : 'Đăng xuất'}</button></header><p role="status" className="text-sm text-orange-800">{message}</p>
 <section className="grid gap-4 sm:grid-cols-2">{data?.profiles.map(p=>{const prog=data.progresses[p.id];const login=data.studentAccounts.find(a=>a.profileId===p.id);return <article key={p.id} className="space-y-3 rounded-2xl border bg-white p-5"><h2 className="text-lg font-bold">{p.avatar} {p.name} · {GRADE_LEVELS.find(g=>g.id===p.gradeId)?.label}</h2><p className="text-sm">{login?`Đăng nhập học sinh: ${login.email}`:'Chưa có đăng nhập riêng. Tạo ở phần bên dưới.'}</p><div className="flex flex-wrap gap-4 text-sm"><span>⭐ {prog?.totalStars??0} sao</span><span>{Object.keys(prog?.wordProgress??{}).length} từ đã luyện</span><span>{prog?.streak??0} ngày liên tiếp</span><span>{Object.values(prog?.storySessions??{}).filter(s=>s.completed).length} bài đọc hoàn thành</span></div><p className="text-sm text-slate-500">Lần học gần nhất: {prog?.lastActiveDate||'Chưa học'}</p><details><summary className="min-h-11 cursor-pointer font-bold">Chi tiết tiến độ</summary>{Object.values(prog?.wordProgress??{}).map(w=><p key={`${w.catId}:${w.wordId}`} className="py-1 text-sm">{[...CATEGORIES, ...(data?.categories??[])].find(c=>c.id===w.catId)?.words.find(word=>word.id===w.wordId)?.en??w.wordId} · {w.stars} sao · {w.attempts} lượt</p>)}<p className="text-sm">{Object.keys(prog?.learningSessions??{}).length} chặng luyện từ trước đây</p>{Object.values(prog?.storySessions??{}).map(s=><p className="py-1 text-sm" key={s.id}>{s.lesson.title} · {s.completed?'Đã hoàn thành':'Đang đọc'} · {s.lesson.questions.filter(q=>s.answers[`quiz:${q.id}`]?.firstCorrect&&!s.answers[`quiz:${q.id}`]?.supported).length}/{s.lesson.questions.length} câu hiểu bài tự làm đúng</p>)}</details><button className="learning-button border" onClick={()=>setEdit({...p})}>Sửa tên & lớp</button></article>;})}</section>
 {edit&&<form className="space-y-3 rounded-2xl border bg-white p-5" onSubmit={async e=>{e.preventDefault();if(await submit({action:'update_student',profileId:edit.id,name:edit.name,gradeId:edit.gradeId}))setEdit(null);}}><h2 className="font-bold">Sửa học sinh</h2><label className="block">Tên<input className={field} required value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label className="block">Lớp<select className={field} value={edit.gradeId} onChange={e=>setEdit({...edit,gradeId:e.target.value})}>{GRADE_LEVELS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><button disabled={busy} className="learning-button bg-orange-600 text-white">Lưu</button><button type="button" className="learning-button" onClick={()=>setEdit(null)}>Hủy</button></form>}
 <div className="grid gap-6 md:grid-cols-2"><form className="space-y-4 rounded-2xl border bg-white p-5" onSubmit={async e=>{e.preventDefault();if(await submit({action:'create_student',name,gradeId:grade,email,password,profileId:profileId||undefined})){setName('');setEmail('');setPassword('');}}}><h2 className="text-lg font-bold">Tạo đăng nhập học sinh</h2><label className="block text-sm">Hồ sơ<select className={field} value={profileId} onChange={e=>{setProfileId(e.target.value);const p=data?.profiles.find(p=>p.id===e.target.value);if(p){setName(p.name);setGrade(p.gradeId);}}}><option value="">Thêm học sinh mới</option>{data?.profiles.filter(p=>!data.studentAccounts.some(a=>a.profileId===p.id)).map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label className="block text-sm">Tên học sinh<input className={field} required value={name} onChange={e=>setName(e.target.value)}/></label><label className="block text-sm">Lớp<select className={field} value={grade} onChange={e=>setGrade(e.target.value)}>{GRADE_LEVELS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label><label className="block text-sm">Email đăng nhập học sinh<input type="email" required className={field} value={email} onChange={e=>setEmail(e.target.value)}/></label><label className="block text-sm">Mật khẩu<input type="password" autoComplete="new-password" minLength={6} required className={field} value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={busy} className="learning-button bg-orange-600 text-white">Tạo tài khoản học sinh</button></form>
 <form className="space-y-4 rounded-2xl border bg-white p-5" onSubmit={e=>{e.preventDefault();void addWord();}}><h2 className="text-lg font-bold">Thêm từ mới cho các bé</h2><p className="text-sm text-slate-500">Kho từ riêng của gia đình, phân theo lớp.</p><label className="block text-sm">Lớp<select className={field} value={grade} onChange={e=>setGrade(e.target.value)}>{GRADE_LEVELS.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label>{[['Chủ đề',topic,setTopic],['Từ tiếng Anh',word,setWord],['Nghĩa tiếng Việt',meaning,setMeaning]].map(([label,value,setter])=><label key={label as string} className="block text-sm">{label as string}<input className={field} required value={value as string} onChange={e=>(setter as (v:string)=>void)(e.target.value)}/></label>)}<button disabled={busy||!data} className="learning-button bg-orange-600 text-white">Lưu từ mới</button><p className="text-sm">{data?.categories.reduce((n,c)=>n+c.words.length,0)??0} từ trong kho gia đình</p></form></div></div></main>;
}

