// =============================================
// VocaKids – Type Definitions
// =============================================

export interface UserProfile {
  id: string;
  name: string;
  avatar: string;
  gradeId: string;
  color: string;
  createdAt: string;
  code?: string; // Mã tài khoản độc nhất (VD: BONG88, BEYEU01)
}

export interface Word {
  id: string;
  en: string;          // English word
  vi: string;          // Vietnamese meaning
  phonetic: string;    // IPA phonetic
  emoji: string;       // Visual emoji
  example_en: string;  // Example sentence (English)
  example_vi: string;  // Example sentence (Vietnamese)
  audio_url?: string;  // Optional pre-recorded audio
  image_url?: string;  // Optional illustration
  kids_phonics?: KidsPhonics; // Vietnamese phonics approximation for children
  topic_vi?: string;   // Vietnamese topic name (e.g. "Động vật", "Trái cây")
  topic_en?: string;   // English topic name (e.g. "Animals", "Fruits")
  topic_emoji?: string;// Topic icon (e.g. "🐾", "🍎")
}

/** Vietnamese Phonics Approximation — generated by Gemini */
export interface KidsPhonics {
  /** Full phonics string. UPPERCASE = stressed syllable, (t)/(s) = ending sounds
   *  e.g. "ÁP-pờl", "bờ-NEN-nờ", "É-li-phần-(t)"
   */
  text: string;
  /** Array of individual syllables for animated syllable-by-syllable display */
  syllables: string[];
  /** Zero-based index of the primary stressed syllable, when verified. */
  stressIndex?: number;
  /** Primary stress positions, including one per word in multiword phrases. */
  stressIndices?: number[];
  /** Ultra-short mouth-tip for children, humorous & memorable */
  mouth_tip: string;
  /** Slow-reading text optimised for TTS (spaces between syllables) */
  audio_slow_text: string;
}

export interface Category {
  id: string;
  name_vi: string;     // Vietnamese category name
  name_en: string;     // English category name
  emoji: string;
  color: string;       // Tailwind accent color class
  gradient: string;    // Tailwind gradient class
  words: Word[];
}

export type LearningMode = 'learn' | 'quiz' | 'speak';

export interface PronunciationResult {
  attemptId: string;
  status: "pass" | "practice" | "retry" | "service_error";
  reason: string;
  contentStatus: "matched" | "partial" | "different" | "unknown";
  passed: boolean | null;
  score: number | null;
  scoreType: "none" | "estimated" | "calibrated";
  feedbackVi: string;
  engineVersion: string;
  rubricVersion: string | null;
  calibrationVersion: string | null;
}

export interface WordProgress {
  lastPronunciationAttemptId?: string;
  wordId: string;
  catId: string;
  stars: number;           // 0–3
  attempts: number;
  bestScore: number;
  lastPracticed: string;   // ISO date string (YYYY-MM-DD)
  consecutivePasses?: number; // Số lần đọc đúng liên tiếp (cần >= 2 để tốt nghiệp)
  mastered?: boolean;         // Đã tốt nghiệp thành thạo chưa
  masteredAt?: string;        // Ngày tốt nghiệp (YYYY-MM-DD)
  reviewDueDate?: string;     // Ngày đến hạn ôn tập tiếp theo (Spaced Repetition)
  intervalDays?: number;      // Khoảng cách chu kỳ ôn tập (1, 3, 7, 14, 30 ngày)
}

export interface DailyStats {
  date: string;
  wordsStudied: number;
  totalStars: number;
  streak: number;
}

// ──────────────────────────────────────────
// Reward / Gamification Types
// ──────────────────────────────────────────

export type StickerTier = 'basic' | 'star' | 'rare' | 'legendary' | 'special';

export interface Sticker {
  id: string;
  name: string;         // e.g. "Mèo Học Giỏi"
  emoji: string;        // e.g. "🐱"
  tier: StickerTier;
  setId: string;        // themed set grouping
  unitId?: string;      // which unit it belongs to
  gradeId?: string;     // which grade level
  condition: string;    // human-readable description of how to earn
  earnedAt: string;     // ISO date when earned
}

export interface Badge {
  id: string;
  name: string;
  description: string;
  emoji: string;
  earnedAt: string;
}

export type UnitTestGrade = 'excellent' | 'good' | 'pass' | 'fail';

export interface UnitTestResult {
  correctAnswers?: number;
  questionCount?: number;
  unitId: string;
  score: number;           // 0–130
  grade: UnitTestGrade;
  completedAt: string;
  attempts: number;
  fastAnswers: number;     // answers within < 3s
  streak: number;          // best streak in the attempt
}

export interface AppProgress {
  progressResetAt?: string;
  stickerStudyDays?: string[];
  ipaPractice?: Record<string, import('@/lib/ipa/practice').IpaPracticeRecord>;
  storySessions?: Record<string, import('@/lib/stories/types').StorySession>;
  deletedStories?: Record<string,string>;
  learningSessions?: Record<string, import('@/lib/learning/types').LearningSession>;
  learningRewardKeys?: string[];
  totalStars: number;
  streak: number;
  lastActiveDate: string;
  wordProgress: Record<string, WordProgress>;
  dailyStats: DailyStats[];

  // ── Gamification (v2) ──
  stickers: Sticker[];
  badges: Badge[];
  unitTestResults: Record<string, UnitTestResult>;  // key = unitId
  unlockedUnits: string[];                           // manually unlocked by admin
  totalPoints: number;                               // cumulative score
}
