import fs from 'fs';

// Helper emoji and sentence dictionary for words
const EMOJI_MAP = {
  'one': '1️⃣', 'two': '2️⃣', 'three': '3️⃣', 'four': '4️⃣', 'five': '5️⃣',
  'six': '6️⃣', 'seven': '7️⃣', 'eight': '8️⃣', 'nine': '9️⃣', 'ten': '🔟',
  'eleven': '1️⃣1️⃣', 'twelve': '1️⃣2️⃣', 'thirteen': '1️⃣3️⃣', 'fourteen': '1️⃣4️⃣', 'fifteen': '1️⃣5️⃣',
  'sixteen': '1️⃣6️⃣', 'seventeen': '1️⃣7️⃣', 'eighteen': '1️⃣8️⃣', 'nineteen': '1️⃣9️⃣', 'twenty': '2️⃣0️⃣',
  'hello': '👋', 'hi': '🙋', 'bye': '👋', 'goodbye': '👋', 'fine': '😊', 'thank you': '🙏', 'how': '❓',
  'name': '🏷️', 'old': '🎂', 'friend': '🤝', 'teacher': '👩‍🏫', 'mr': '👨‍💼', 'ms': '👩‍💼',
  'this': '👉', 'that': '👉', 'yes': '✅', 'no': '❌',
  'ear': '👂', 'eye': '👁️', 'face': '😊', 'hair': '💇', 'hand': '✋', 'mouth': '👄', 'nose': '👃', 'open': '👐', 'touch': '👆',
  'cooking': '🍳', 'dancing': '💃', 'drawing': '🎨', 'painting': '🖌️', 'running': '🏃', 'singing': '🎤', 'swimming': '🏊', 'walking': '🚶',
  'art room': '🎨', 'classroom': '🏫', 'computer room': '💻', 'gym': '🏋️', 'library': '📚', 'music room': '🎵', 'playground': '🛝', 'school': '🏫',
  'close': '🚪', 'come in': '🚶', 'go out': '🚪', 'sit down': '🪑', 'speak': '🗣️', 'stand up': '🧍',
  'book': '📖', 'eraser': '🧼', 'notebook': '📓', 'pen': '🖊️', 'pencil': '✏️', 'pencil case': '👝', 'ruler': '📏', 'school bag': '🎒',
  'black': '⚫', 'blue': '🔵', 'brown': '🟤', 'colour': '🎨', 'green': '🟢', 'orange': '🟠', 'red': '🔴', 'white': '⚪', 'yellow': '🟡',
  'break time': '⏰', 'chat': '💬', 'do word puzzles': '🧩', 'play badminton': '🏸', 'play basketball': '🏀', 'play chess': '♟️', 'play football': '⚽', 'play table tennis': '🏓', 'play volleyball': '🏐',
  'brother': '👦', 'father': '👨', 'mother': '👩', 'sister': '👧', 'sure': '👌',
  'cook': '👨‍🍳', 'doctor': '👨‍⚕️', 'driver': '🚗', 'farmer': '👨‍🌾', 'job': '💼', 'nurse': '👩‍⚕️', 'singer': '🎤', 'worker': '👷',
  'bathroom': '🛁', 'bedroom': '🛏️', 'chair': '🪑', 'house': '🏡', 'kitchen': '🍳', 'lamp': '💡', 'living room': '🛋️', 'table': '🪑', 'in': '📥', 'on': '🔝', 'here': '📍', 'there': '👉',
  'bed': '🛏️', 'big': '🐘', 'desk': '🪑', 'door': '🚪', 'new': '✨', 'room': '🚪', 'small': '🐭', 'window': '🪟',
  'bean': '🫘', 'bread': '🍞', 'chicken': '🍗', 'egg': '🥚', 'fish': '🐟', 'juice': '🧃', 'meat': '🥩', 'milk': '🥛', 'rice': '🍚', 'water': '💧',
  'bird': '🐦', 'cat': '🐱', 'dog': '🐶', 'goldfish': '🐠', 'parrot': '🦜', 'rabbit': '🐰', 'many': '🔢', 'some': '🥣',
  'bus': '🚌', 'car': '🚗', 'kite': '🪁', 'plane': '✈️', 'ship': '🚢', 'teddy bear': '🧸', 'toy': '🧸', 'train': '🚂', 'truck': '🚚',
  'drawing a picture': '🎨', 'listening to music': '🎧', 'playing basketball': '🏀', 'reading': '📖', 'watching tv': '📺', 'writing': '✍️',
  'cycling': '🚴', 'flying a kite': '🪁', 'playing badminton': '🏸', 'skating': '🛼', 'skipping': '🪢',
  'climbing': '🧗', 'counting': '🔢', 'elephant': '🐘', 'horse': '🐎', 'monkey': '🐒', 'peacock': '🦚', 'swinging': '🐒', 'tiger': '🐯',
  'board': '📋', 'bookcase': '📚', 'crayon': '🖍️', 'cupboard': '🗄️', 'map': '🗺️', 'paper': '📄', 'poster': '🖼️', 'rubber': '🧼', 'scissors': '✂️', 'sharpener': '✏️',
  'grandfather': '👴', 'grandmother': '👵', 'grandparents': '👵👴', 'uncle': '👨', 'aunt': '👩', 'cousin': '🧑', 'parents': '👩👨', 'baby': '👶',
  'garden': '🌳', 'hall': '🏛️', 'balcony': '🏢', 'clock': '⏰', 'mirror': '🪞', 'sofa': '🛋️', 'armchair': '🪑', 'carpet': '🧶', 'picture': '🖼️', 'television': '📺',
  'apple': '🍎', 'banana': '🍌', 'burger': '🍔', 'candy': '🍬', 'lemonade': '🍋', 'mango': '🥭', 'sausage': '🌭', 'watermelon': '🍉',
  'bear': '🐻', 'crocodile': '🐊', 'duck': '🦆', 'frog': '🐸', 'giraffe': '🦒', 'hippo': '🦛', 'lizard': '🦎', 'mouse': '🐭', 'sheep': '🐑', 'spider': '🕷️',
  'clothes': '👗', 'dress': '👗', 'hat': '👒', 'jacket': '🧥', 'jeans': '👖', 'shirt': '👔', 'shoes': '👟', 'skirt': '🩰', 'socks': '🧦', 'trousers': '👖',
  'weather': '🌤️', 'sunny': '☀️', 'rainy': '🌧️', 'windy': '💨', 'cloudy': '☁️', 'cold': '🥶', 'hot': '🥵', 'spring': '🌸', 'summer': '☀️', 'winter': '❄️',
  'bicycle': '🚲', 'motorbike': '🛵', 'helicopter': '🚁', 'boat': '⛵', 'taxi': '🚕', 'lorry': '🚛', 'station': '🚉',
  'happy': '😊', 'sad': '😢', 'angry': '😠', 'tired': '🥱', 'hungry': '😋', 'thirsty': '🥤', 'clever': '🧠', 'friendly': '🤝', 'funny': '😄', 'kind': '❤️',
  'good morning!': '🌅', 'good afternoon!': '☀️', 'good evening!': '🌆', 'nice to meet you.': '🤝', 'here you are.': '🎁', "you're welcome.": '😊', 'pardon?': '👂', 'see you later!': '👋'
};

const CATEGORY_META = [
  { raw: 'STARTER', id: 'lop3_starter', name_vi: 'Starter: Khởi Động Số Đếm', name_en: 'Starter: Numbers', emoji: '🔢', color: 'from-teal-400 to-cyan-500', gradient: 'bg-gradient-to-br from-teal-100 to-cyan-100' },
  { raw: 'UNIT 1: HELLO', id: 'lop3_unit1', name_vi: 'Unit 1: Xin Chào', name_en: 'Unit 1: Hello', emoji: '👋', color: 'from-cyan-400 to-blue-500', gradient: 'bg-gradient-to-br from-cyan-100 to-blue-100' },
  { raw: 'UNIT 2: OUR NAMES', id: 'lop3_unit2', name_vi: 'Unit 2: Tên Của Chúng Mình', name_en: 'Unit 2: Our Names', emoji: '🏷️', color: 'from-blue-400 to-indigo-500', gradient: 'bg-gradient-to-br from-blue-100 to-indigo-100' },
  { raw: 'UNIT 3: OUR FRIENDS', id: 'lop3_unit3', name_vi: 'Unit 3: Bạn Bè Của Chúng Mình', name_en: 'Unit 3: Our Friends', emoji: '🤝', color: 'from-indigo-400 to-purple-500', gradient: 'bg-gradient-to-br from-indigo-100 to-purple-100' },
  { raw: 'UNIT 4: OUR BODIES', id: 'lop3_unit4', name_vi: 'Unit 4: Cơ Thể Của Chúng Mình', name_en: 'Unit 4: Our Bodies', emoji: '👤', color: 'from-purple-400 to-pink-500', gradient: 'bg-gradient-to-br from-purple-100 to-pink-100' },
  { raw: 'UNIT 5: MY HOBBIES', id: 'lop3_unit5', name_vi: 'Unit 5: Sở Thích Của Tôi', name_en: 'Unit 5: My Hobbies', emoji: '🎨', color: 'from-pink-400 to-rose-500', gradient: 'bg-gradient-to-br from-pink-100 to-rose-100' },
  { raw: 'UNIT 6: OUR SCHOOL', id: 'lop3_unit6', name_vi: 'Unit 6: Trường Học Của Chúng Mình', name_en: 'Unit 6: Our School', emoji: '🏫', color: 'from-emerald-400 to-teal-500', gradient: 'bg-gradient-to-br from-emerald-100 to-teal-100' },
  { raw: 'UNIT 7: CLASSROOM INSTRUCTIONS', id: 'lop3_unit7', name_vi: 'Unit 7: Khẩu Lệnh Trong Lớp', name_en: 'Unit 7: Classroom Instructions', emoji: '📢', color: 'from-teal-400 to-green-500', gradient: 'bg-gradient-to-br from-teal-100 to-green-100' },
  { raw: 'UNIT 8: MY SCHOOL THINGS', id: 'lop3_unit8', name_vi: 'Unit 8: Đồ Dùng Học Tập Của Tôi', name_en: 'Unit 8: My School Things', emoji: '🎒', color: 'from-green-500 to-emerald-600', gradient: 'bg-gradient-to-br from-green-100 to-emerald-100' },
  { raw: 'UNIT 9: COLOURS', id: 'lop3_unit9', name_vi: 'Unit 9: Màu Sắc', name_en: 'Unit 9: Colours', emoji: '🎨', color: 'from-amber-400 to-orange-500', gradient: 'bg-gradient-to-br from-amber-100 to-orange-100' },
  { raw: 'UNIT 10: BREAK TIME ACTIVITIES', id: 'lop3_unit10', name_vi: 'Unit 10: Hoạt Động Giờ Ra Chơi', name_en: 'Unit 10: Break Time Activities', emoji: '⚽', color: 'from-orange-400 to-rose-500', gradient: 'bg-gradient-to-br from-orange-100 to-rose-100' },
  { raw: 'UNIT 11: MY FAMILY', id: 'lop3_unit11', name_vi: 'Unit 11: Gia Đình Của Tôi', name_en: 'Unit 11: My Family', emoji: '👨‍👩‍👧‍👦', color: 'from-rose-400 to-pink-500', gradient: 'bg-gradient-to-br from-rose-100 to-pink-100' },
  { raw: 'UNIT 12: JOBS', id: 'lop3_unit12', name_vi: 'Unit 12: Nghề Nghiệp', name_en: 'Unit 12: Jobs', emoji: '💼', color: 'from-cyan-500 to-blue-600', gradient: 'bg-gradient-to-br from-cyan-100 to-blue-100' },
  { raw: 'UNIT 13: MY HOUSE', id: 'lop3_unit13', name_vi: 'Unit 13: Ngôi Nhà Của Tôi', name_en: 'Unit 13: My House', emoji: '🏡', color: 'from-blue-500 to-indigo-600', gradient: 'bg-gradient-to-br from-blue-100 to-indigo-100' },
  { raw: 'UNIT 14: MY BEDROOM', id: 'lop3_unit14', name_vi: 'Unit 14: Phòng Ngủ Của Tôi', name_en: 'Unit 14: My Bedroom', emoji: '🛏️', color: 'from-indigo-500 to-purple-600', gradient: 'bg-gradient-to-br from-indigo-100 to-purple-100' },
  { raw: 'UNIT 15: AT THE DINING TABLE', id: 'lop3_unit15', name_vi: 'Unit 15: Trên Bàn Ăn', name_en: 'Unit 15: At the Dining Table', emoji: '🍽️', color: 'from-purple-500 to-pink-600', gradient: 'bg-gradient-to-br from-purple-100 to-pink-100' },
  { raw: 'UNIT 16: MY PETS', id: 'lop3_unit16', name_vi: 'Unit 16: Thú Cưng Của Tôi', name_en: 'Unit 16: My Pets', emoji: '🐶', color: 'from-emerald-400 to-teal-500', gradient: 'bg-gradient-to-br from-emerald-100 to-teal-100' },
  { raw: 'UNIT 17: OUR TOYS', id: 'lop3_unit17', name_vi: 'Unit 17: Đồ Chơi Của Chúng Mình', name_en: 'Unit 17: Our Toys', emoji: '🧸', color: 'from-teal-400 to-cyan-500', gradient: 'bg-gradient-to-br from-teal-100 to-cyan-100' },
  { raw: 'UNIT 18: PLAYING AND DOING', id: 'lop3_unit18', name_vi: 'Unit 18: Vui Chơi & Hoạt Động', name_en: 'Unit 18: Playing and Doing', emoji: '🎮', color: 'from-cyan-400 to-blue-500', gradient: 'bg-gradient-to-br from-cyan-100 to-blue-100' },
  { raw: 'UNIT 19: OUTDOOR ACTIVITIES', id: 'lop3_unit19', name_vi: 'Unit 19: Hoạt Động Ngoài Trời', name_en: 'Unit 19: Outdoor Activities', emoji: '🚴', color: 'from-lime-400 to-green-500', gradient: 'bg-gradient-to-br from-lime-100 to-green-100' },
  { raw: 'UNIT 20: AT THE ZOO', id: 'lop3_unit20', name_vi: 'Unit 20: Ở Sở Thú', name_en: 'Unit 20: At the Zoo', emoji: '🦁', color: 'from-amber-500 to-yellow-500', gradient: 'bg-gradient-to-br from-amber-100 to-yellow-100' },
  { raw: 'CHỦ ĐỀ 1: LỚP HỌC & ĐỒ DÙNG HỌC TẬP MỞ RỘNG (SCHOOL & CLASSROOM)', id: 'lop3_ext_school', name_vi: 'Lớp Học & Dụng Cụ Mở Rộng', name_en: 'School & Classroom Plus', emoji: '📐', color: 'from-teal-400 to-cyan-500', gradient: 'bg-gradient-to-br from-teal-100 to-cyan-100' },
  { raw: 'CHỦ ĐỀ 2: GIA ĐÌNH & NGƯỜI THÂN (EXTENDED FAMILY)', id: 'lop3_ext_family', name_vi: 'Đại Gia Đình & Người Thân', name_en: 'Extended Family', emoji: '👨‍👩‍👧‍👦', color: 'from-rose-400 to-pink-500', gradient: 'bg-gradient-to-br from-rose-100 to-pink-100' },
  { raw: 'CHỦ ĐỀ 3: NGÔI NHÀ & NỘI THẤT (HOUSE & FURNITURE)', id: 'lop3_ext_furniture', name_vi: 'Ngôi Nhà & Nội Thất', name_en: 'House & Furniture', emoji: '🛋️', color: 'from-blue-400 to-indigo-500', gradient: 'bg-gradient-to-br from-blue-100 to-indigo-100' },
  { raw: 'CHỦ ĐỀ 4: THỰC PHẨM & ĐỒ UỐNG MỞ RỘNG (FOOD & DRINKS)', id: 'lop3_ext_food', name_vi: 'Món Ngon & Đồ Uống Mở Rộng', name_en: 'Food & Drinks Plus', emoji: '🍔', color: 'from-orange-400 to-amber-500', gradient: 'bg-gradient-to-br from-orange-100 to-amber-100' },
  { raw: 'CHỦ ĐỀ 5: THẾ GIỚI ĐỘNG VẬT (ANIMALS & NATURE)', id: 'lop3_ext_animals', name_vi: 'Thế Giới Động Vật Hoang Dã', name_en: 'Animals & Nature', emoji: '🦒', color: 'from-emerald-400 to-green-500', gradient: 'bg-gradient-to-br from-emerald-100 to-green-100' },
  { raw: 'CHỦ ĐỀ 6: TRANG PHỤC & PHỤ KIỆN (CLOTHES & ACCESSORIES)', id: 'lop3_ext_clothes', name_vi: 'Trang Phục & Phụ Kiện', name_en: 'Clothes & Accessories', emoji: '👗', color: 'from-purple-400 to-pink-500', gradient: 'bg-gradient-to-br from-purple-100 to-pink-100' },
  { raw: 'CHỦ ĐỀ 7: THỜI TIẾT & BỐN MÙA (WEATHER & SEASONS)', id: 'lop3_ext_weather', name_vi: 'Thời Tiết & Bốn Mùa', name_en: 'Weather & Seasons', emoji: '🌤️', color: 'from-sky-400 to-cyan-500', gradient: 'bg-gradient-to-br from-sky-100 to-cyan-100' },
  { raw: 'CHỦ ĐỀ 8: PHƯƠNG TIỆN GIAO THÔNG (TRANSPORTATION)', id: 'lop3_ext_transport', name_vi: 'Phương Tiện Giao Thông Mở Rộng', name_en: 'Transportation Plus', emoji: '🚁', color: 'from-cyan-400 to-teal-500', gradient: 'bg-gradient-to-br from-cyan-100 to-teal-100' },
  { raw: 'CHỦ ĐỀ 9: CẢM XÚC & TÍNH CÁCH (EMOTIONS & DESCRIPTIONS)', id: 'lop3_ext_emotions', name_vi: 'Cảm Xúc & Tính Cách', name_en: 'Emotions & Descriptions', emoji: '💖', color: 'from-amber-400 to-rose-400', gradient: 'bg-gradient-to-br from-amber-100 to-rose-100' },
  { raw: 'CHỦ ĐỀ 10: MẪU CÂU GIAO TIẾP HẰNG NGÀY CHO LỚP 3', id: 'lop3_ext_daily', name_vi: 'Giao Tiếp Hằng Ngày Lớp 3', name_en: 'Daily Communication', emoji: '💬', color: 'from-indigo-400 to-purple-500', gradient: 'bg-gradient-to-br from-indigo-100 to-purple-100' },
];

console.log('Category metadata configured for all 31 categories.');
