'use client';
import {useEffect,useState} from 'react';
import type {MediaAudio} from '@/lib/media/store';
const field='min-h-11 w-full rounded-xl border border-slate-300 bg-white px-3 py-2';
export function MediaOptions(){
  const [settings,setSettings]=useState({enabled:false,voiceId:'',model:'eleven_flash_v2_5',speed:0.85,configured:false});
  const [key,setKey]=useState(''),[text,setText]=useState('Hello! Welcome to our English lesson.'),[items,setItems]=useState<MediaAudio[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function refresh(){const r=await fetch('/api/admin/media');if(!r.ok)throw new Error('Không tải được Media.');const data=await r.json();setSettings(data.settings);setItems(data.items);}
  useEffect(()=>{const controller=new AbortController();void fetch('/api/admin/media',{signal:controller.signal}).then(async r=>{if(!r.ok)throw new Error('Không tải được Media.');return r.json();}).then(data=>{if(!controller.signal.aborted){setSettings(data.settings);setItems(data.items);}}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return ()=>controller.abort();},[]);
  async function save(){setBusy(true);try{const r=await fetch('/api/admin/media',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({...settings,apiKey:key||undefined})});const data=await r.json();if(!r.ok)throw new Error(data.message);setSettings(data);setKey('');setMessage('Đã lưu cấu hình giọng đọc trên server.');}catch(e){setMessage(e instanceof Error?e.message:'Không lưu được.');}finally{setBusy(false);}}
  async function generate(){setBusy(true);setMessage('Đang tạo và lưu audio…');try{const r=await fetch('/api/admin/media/tts',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({text})});const data=await r.json();if(!r.ok)throw new Error(data.message);await refresh();setMessage('Đã lưu MP3 vào Media. Nội dung trùng sẽ dùng lại audio có sẵn.');}catch(e){setMessage(e instanceof Error?e.message:'Không tạo được.');}finally{setBusy(false);}}
  return <section className="space-y-4 rounded-2xl border bg-white p-6"><h2 className="text-lg font-bold">Media · Giọng đọc ElevenLabs</h2><p className="text-sm text-slate-500">Audio được tạo khi admin/phụ huynh bấm nghe, lưu trên server và dùng lại cho từ vựng, câu mẫu, bài đọc. Học sinh nghe bản đã có; khi chưa có audio, app dùng giọng trình duyệt.</p><label className="flex items-center gap-3"><input type="checkbox" checked={settings.enabled} onChange={e=>setSettings({...settings,enabled:e.target.checked})}/>Bật tạo và lưu audio ElevenLabs</label><label className="block text-sm">API key {settings.configured?'· Đã cấu hình':''}<input type="password" autoComplete="new-password" className={field} value={key} onChange={e=>setKey(e.target.value)} placeholder="Nhập key mới; để trống giữ key đang lưu"/></label><label className="block text-sm">Voice ID<input className={field} value={settings.voiceId} onChange={e=>setSettings({...settings,voiceId:e.target.value})} placeholder="Voice ID từ ElevenLabs"/></label><label className="block text-sm">Model<select className={field} value={settings.model} onChange={e=>setSettings({...settings,model:e.target.value})}><option value="eleven_flash_v2_5">Flash v2.5</option><option value="eleven_multilingual_v2">Multilingual v2</option></select></label><label className="block text-sm">Tốc độ tạo audio ({settings.speed}×)<input type="range" min={0.7} max={1.2} step={0.05} value={settings.speed} onChange={e=>setSettings({...settings,speed:Number(e.target.value)})} className="mt-2 w-full"/><span className="text-xs text-slate-500">0.7× chậm · 0.85× luyện nghe · 1× bình thường. Lưu cấu hình trước khi tạo audio.</span></label><button disabled={busy} className="learning-button bg-orange-600 text-white disabled:opacity-50" onClick={()=>void save()}>Lưu cấu hình giọng đọc</button><label className="block text-sm">Từ, câu hoặc đoạn văn cần tạo<textarea className={field} rows={4} maxLength={6000} value={text} onChange={e=>setText(e.target.value)}/></label><button disabled={busy||!text.trim()||!settings.enabled||!settings.configured||!settings.voiceId} className="learning-button border bg-white disabled:opacity-50" onClick={()=>void generate()}>{busy?'Đang xử lý…':'Tạo và lưu vào Media'}</button><p role="status" className="text-sm text-orange-800">{message}</p><h3 className="font-bold">Audio đã lưu ({items.length})</h3><div className="max-h-96 space-y-3 overflow-auto">{items.map(item=><article key={item.id} className="rounded-xl border p-3"><p className="mb-2 text-sm">{item.text}</p><p className="mb-2 text-xs text-slate-500">Tốc độ tạo: {item.speed??1}×</p><audio controls preload="none" src={item.url} className="max-w-full"/><a className="text-sm text-orange-700" href={item.url} download={`${item.id}.mp3`}>Tải MP3</a></article>)}</div></section>;
}
